# App: argocd/my-app-e2e-east (https://localhost:8080/applications/argocd/my-app-e2e-east)
# Commit: 8bda8c47ad9b72f165af37e82c759449e2be2d2e Michael Crenshaw <350466+crenshaw-dev@users.noreply.github.com> bump tag version Signed-off-by: Michael Crenshaw <350466+crenshaw-dev@users.noreply.github.com>
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-deployment-e2e-east
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: my-container
        ports:
        - containerPort: 80
